[package]
name = "stacorust"
version = "0.1.0"
authors = ["Yax"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.14.0"
imap = "1.0.2"
lettre = "0.9.2"